### PR TITLE
Add badges to readme

### PR DESCRIPTION
**Pull request by ahuang11**
## Summary

Was intrigued by: https://github.com/fugue-project/prefect-fugue

Codecov requires an account so I left that out.

Wanted to see how it would look for our collections. if good, let's add this to prefect-collection-template
image

### CODE REVIEW

**Comment by ahuang11** [comment]
Works in docs too
image

**Comment by discdiver** [comment]
This is a good idea!

**Comment by ahuang11** [comment]
There's also tests + static analysis, but I think it might be too much
```
[![Tests](https://github.com/prefecthq/prefect-aws/workflows/Tests/badge.svg)](https://github.com/PrefectHQ/prefect-aws/blob/main/.github/workflows/tests.yml)
[![Lint](https://github.com/prefecthq/prefect-aws/workflows/Static%20analysis/badge.svg)](https://github.com/PrefectHQ/prefect-aws/blob/main/.github/workflows/static_analysis.yml)
```

image

**Comment by ahuang11** [comment]
And contributors...
`[Contributors](https://github.com/prefecthq/prefect-aws/graphs/contributors)`
image

But probably more suited for the main repo

**Comment by desertaxle** [comment]
We also use `README.md` for the package description on PyPI, so I'd want to verify that these badges work there as well.

**Comment by ahuang11** [comment]
Pretty sure they do. I copied some of the badges from: https://pypi.org/project/climpred/ which comes from their readme too
https://github.com/pangeo-data/climpred/blob/main/README.rst

**Comment by ahuang11** [comment]
image

**Review by desertaxle — APPROVED** [review]

**Pull request merged**
