### PR TITLE
Handle boto3 clients more efficiently with lru_cache

### LINKED ISSUE #332: put_directory creates a new s3_client for each file uploaded
Hello all, 

I am executing `build_from_flow` as below to upload all my Prefect files into an `S3Bucket`.

```python
Deployment.build_from_flow(
    flow=...,
    skip_upload=False,
    storage: Block = S3Bucket.load(...),
    ...,
)
``` 

It works, but the result is that `upload_to_storage` takes a very long time. I have about 400 files to upload and it takes around 1 second per file. 
I looked at the source code and the `botocore` output and it looks like a boto3 client and credentials are checked for every files.

version: `prefect-aws==0.4.1`

# Expectation / Proposal

Uploading a bunch of files to S3 should very fast.

# Traceback / Example

- [x] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

### PR DESCRIPTION
**Pull request by mattiamatrix**
Closes #332

### Checklist

- [x] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-aws/issues/new/choose) first.
- [x] Includes tests or only affects documentation.
- [x] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [x] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-aws/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by mattiamatrix** [comment]
> Thanks for the contribution @mattiamatrix! This looks like a great optimization, but I'd like to suggest some tweaks:
> 
> 1. I think we should move the changes into the `get_client` method so all the client types can benefit from this optimization.
> 2. We should maintain a cache of clients with their parameters as the cache key. In the current implementation, if any attributes are changed on the class, the client returned would not be updated to reflect those changes. By introducing a LRU cache, we can improve performance while maintaining configurability on the fly.
> 
> Let me know if you'd like me to go into more detail for either of those points!

Thank you for the review @desertaxle. I made the changes as you described. Let me know what you think now. 
I had to add a little bit of code to follow pydantic/pydantic#3376.

**Comment by mattiamatrix** [comment]
Hello @desertaxle @zzstoatzz, is the PR ok now?

**Comment by zzstoatzz** [comment]
hi @mattiamatrix - Alex is currently out-of-office for a while, so I can take over reviewing this.

Let me take a look here / get caught up and do some QA and I will get back to you on this - appreciate the contribution! 🙂

**Comment by zzstoatzz** [comment]
hey @mattiamatrix - this looks pretty good to me. Can you add a test for the new functionality, maybe something like this?

```python
from prefect_aws.credentials import _get_client_cached, AwsCredentials, ClientType
from unittest.mock import patch

@patch('prefect_aws.credentials._get_client_cached')
def test_get_client_cached(mock_get_client_cached):
    """
    Test to ensure that _get_client_cached function returns the same instance
    for multiple calls with the same parameters and properly utilizes lru_cache.
    """

    # Create a mock AwsCredentials instance
    aws_credentials_block = AwsCredentials()

    # Call _get_client_cached multiple times with the same parameters
    _get_client_cached(aws_credentials_block, ClientType.S3)
    _get_client_cached(aws_credentials_block, ClientType.S3)

    # Verify that _get_client_cached is called only once due to caching
    mock_get_client_cached.assert_called_once_with(aws_credentials_block, ClientType.S3)

    # Optionally, you can test with different parameters to ensure they are cached separately
    _get_client_cached(aws_credentials_block, ClientType.ECS)
    assert mock_get_client_cached.call_count == 2, "Should be called twice with different parameters"
```

**Comment by mattiamatrix** [comment]
Hi @zzstoatzz, thank you for the snippet. I added the code that you shared but the test is failing with error `AssertionError: Expected '_get_client_cached' to be called once. Called 0 times.` since `call_count` is always `0`.  

@zzstoatzz it would be very helpful if you could directly update the code and push the correct test. Thank you.

**Comment by zzstoatzz** [comment]
sorry @mattiamatrix - i should have clarified that that was pseudocode based on my memory of the mocks / fixtures available

i do not have time to do this now but if you're unable then I can come back to this later

**Comment by mattiamatrix** [comment]
> sorry @mattiamatrix - i should have clarified that that was pseudocode based on my memory of the mocks / fixtures available
> 
> i do not have time to do this now but if you're unable then I can come back to this later

Ok, I pushed a version that is using `cache_info()` instead to get a similar result.

**Comment by zzstoatzz** [comment]
hi @mattiamatrix - after discussing this internally, I think we should change how we're getting that `__hash__`

as is:
- if you changed field values, we'd still hit the cache since we're just looking at the `id`
- successively loaded instances of `AwsCredentials` would not hit the cache (share clients) because they would have different values for `id`

instead of just the `id`, the `__hash__` should be derived from the hashes of all the values of all the fields on `AwsCredentials` (or alternatively, we could just use the underlying return value of `get_params_override` as the cache key instead of the `AwsCredentials` object)

**Comment by mattiamatrix** [comment]
@desertaxle @zzstoatzz updated the `__hash__` funcition to

```py
def __hash__(self):
	return hash(self.json())
```

For any further request please feel free to implement it. It would be great to have this PR merged soon.

**Comment by mattiamatrix** [comment]
Close in favour of https://github.com/PrefectHQ/prefect-aws/pull/369

**Pull request closed without merging**
