### PR TITLE
Fix `S3Bucket.copy_object` target path resolution

### LINKED ISSUE #384: `S3Bucket.copy_object`: Only resolve target path with self if `to_bucket` is not defined
`S3Bucket.copy_object` resolves the target path using the source bucket, regardless of whether the object goes to the source bucket or elsewhere.

https://github.com/PrefectHQ/prefect-aws/blob/87755b2d7fd979d7975486abdd56f2e4d191e2f7/prefect_aws/s3.py#L1238

# Expectation / Proposal

- Resolve the target path with `self` when the object is being copied within the bucket
- Resolve the target path with the `to_bucket` when the object is being copied to it and it is an `S3Bucket`

# Traceback / Example

- [x] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

### PR DESCRIPTION
**Pull request by dominictarro**
Closes #384

Uses other bucket's `_resolve_path` method when copying to another `S3Bucket` object. If `to_bucket` is a string, doesn't resolve. Copies to `self` when `to_bucket` is None.

### Example

```python
from prefect_aws import S3Bucket

source = S3Bucket(bucket_name="source-bucket")
target = S3Bucket(bucket_name="target-bucket", bucket_folder="subpath/")
source.copy_object("abc.txt", "copies/abc.txt", target)
# subpath/copies/abc.txt
```

### Checklist

- [x] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-aws/issues/new/choose) first.
- [x] Includes tests or only affects documentation.
- [x] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.

### CODE REVIEW

**Comment by dominictarro** [comment]
Unclear what's up with the error message. Did something break in main?

> AttributeError: 'CallSpec2' object has no attribute 'funcargs'

**Comment by zzstoatzz** [comment]
hey @dominictarro - that's because we hadn't yet pinned pytest. that change is merged now and we should be back to normal here. thanks for catching!

**Comment by dominictarro** [comment]
I just noticed that the same issue is in the move methods, so don't merge yet. Going to revisit this when I have time.

**Comment by dominictarro** [comment]
This is ready for review.

**Pull request merged**
