### PR TITLE
feat(ecs.py): adding the allow_task_definition_registration boolean to offer ability to disable task definition registration handling

### LINKED ISSUE #235: Provide the option to disable all task definition registration handling if task definition arn is provided
# Expectation / Proposal

IMO we should provide the option to disable all task definition registration handling if task definition arn is provided.

I feel like doing some of the guess work for a user with less AWS experience is fine, but when building a more self service approach to adopting Prefect, a more hands off approach the the task definition my be preferred.

For example,  I want to have complete control over the task definition, so that I can create reliable extractions for flow deployment.  If a task definition is already created with things like mounts, log configuration, secrets, then all I want is the ability to run the task with access to the `run_task` overrides.  This is not the case currently.  Even with a task definition arn provided, if my task definition has certain properties, the agent will try and make a new one.

I am perfectly fine handling diff based registration myself given that I want to provide very specific keys that trigger a new task definition. 

# Traceback / Example

Here is a task definition python example where agent will do nothing other than run task:

```python
"family": task_name,
            "taskRoleArn": task_role_arn,
            "executionRoleArn": execution_role_arn,
            "networkMode": "awsvpc",
            "containerDefinitions": [
                {
                    "name": default_container_name,
                    "image": image_name,
                    "environment": [
                        {"name": "PREFECT_DISABLE_FLOW_SPEC", "value": "true"},
                    ],
                    "secrets": secrets,
                }
            ],
            "requiresCompatibilities": [
                "FARGATE",
            ],
            "cpu": default_cpu,
            "memory": default_memory,
            "ephemeralStorage": {"sizeInGiB": ephemeral_storage},
        }
```

However this triggers the task definition registration handling:

```python
"family": task_name,
            "taskRoleArn": task_role_arn,
            "executionRoleArn": execution_role_arn,
            "networkMode": "awsvpc",
            "containerDefinitions": [
                {
                    "name": default_container_name,
                    "image": image_name,
                    "environment": [
                        {"name": "PREFECT_DISABLE_FLOW_SPEC", "value": "true"},
                    ],
                    "secrets": secrets,
                    "logConfiguration": {
                        "logDriver": "awslogs",
                        "options": {
                            "awslogs-create-group": "true",
                            "awslogs-group": default_container_name,
                            "awslogs-region": AWS_REGION,
                            "awslogs-stream-prefix": task_name,
                        },
                    },
                }
            ],
            "requiresCompatibilities": [
                "FARGATE",
            ],
            "cpu": default_cpu,
            "memory": default_memory,
            "ephemeralStorage": {"sizeInGiB": ephemeral_storage},
        }
```

Here is an example of how I want to handle diff myself:

```python
def _handle_task_definition(self):
        register = False
        final_task_def_arn = None
        task_name = f"{self._slugified_flow_name}-{DEPLOYMENT_TYPE}"
        account_id = get_aws_account_id()
        init_session = session.Session()
        ecs = init_session.client("ecs")
        image_name = f"{account_id}.dkr.ecr.{AWS_REGION}.amazonaws.com/data-flows-prefect-envs:{self.docker_env}-{GIT_SHA}"
        task_role_arn = f"arn:aws:iam::{account_id}:role/data-flows-prefect-{DEPLOYMENT_TYPE}-task-role"
        execution_role_arn = f"arn:aws:iam::{account_id}:role/data-flows-prefect-{DEPLOYMENT_TYPE}-exec-role"
        secrets = [
            {
                "name": i.envar_name,
                "valueFrom": f"arn:aws:secretsmanager:{AWS_REGION}:{account_id}:secret:{i.secret_name}",
            }
            for i in self.secrets
        ]
        ephemeral_storage = self.ephemeral_storage_gb
        default_cpu = "256"
        default_memory = "512"

        task_def_compare_keys = [
            "taskRoleArn",
            "executionRoleArn",
            "requiresCompatibilities",
            "cpu",
            "memory",
            "ephemeralStorage",
        ]

        container_def_compare_keys = ["image", "environment", "secrets", "logConfiguration"]
        
        default_container_name = "prefect-flow"

        new_task_def_dict = {
            "family": task_name,
            "taskRoleArn": task_role_arn,
            "executionRoleArn": execution_role_arn,
            "networkMode": "awsvpc",
            "containerDefinitions": [
                {
                    "name": default_container_name,
                    "image": image_name,
                    "environment": [
                        {"name": "PREFECT_DISABLE_FLOW_SPEC", "value": "true"},
                    ],
                    "secrets": secrets,
                    "logConfiguration": {
                        "logDriver": "awslogs",
                        "options": {
                            "awslogs-create-group": "true",
                            "awslogs-group": default_container_name,
                            "awslogs-region": AWS_REGION,
                            "awslogs-stream-prefix": task_name,
                        },
                    },
                }
            ],
            "requiresCompatibilities": [
                "FARGATE",
            ],
            "cpu": default_cpu,
            "memory": default_memory,
            "ephemeralStorage": {"sizeInGiB": ephemeral_storage},
        }

        task_def_arns = ecs.list_task_definitions(familyPrefix=task_name, maxResults=5)
        if task_def_arns["taskDefinitionArns"]:
            current_task_def_response = ecs.describe_task_definition(
                taskDefinition=task_name
            )
            current_task_def = current_task_def_response["taskDefinition"]
            final_task_def_arn = current_task_def["taskDefinitionArn"]
            if not all(
                new_task_def_dict.get(key) == current_task_def.get(key)
                for key in task_def_compare_keys
            ):
                LOGGER.info(
                    f"Task definition state has changed for {task_name}, registering new definition..."
                )
                register = True
            elif not all(
                new_task_def_dict.get("containerDefinitions", [{}])[0].get(key)
                == current_task_def.get("containerDefinitions", [{}])[0].get(key)
                for key in container_def_compare_keys
            ):
                LOGGER.info(
                    f"Task definition state has changed for {task_name}, registering new definition..."
                )
                register = True

        else:
            LOGGER.info(
                f"Task definition not registered for {task_name}, registering new definition..."
            )
            register = True

        if register:
            response = ecs.register_task_definition(**new_task_def_dict)
            final_task_def_arn = response["taskDefinition"]["taskDefinitionArn"]
        else:
            LOGGER.info(
                f"Task definition state has not changed {task_name}, new revision not needed..."
            )
        return final_task_def_arn
```

- [X] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

### PR DESCRIPTION
**Pull request by braunreyes**
Closes #235.

Per the comment on the issue, I am adding a new argument to the ECSTask Class called `allow_task_definition_registration`.

This will default to True, but act as a way to disable the task registration logic if set to False.  This means that the task definition arn provided is the exact task definition that will be used.

This makes it so the task definition is more static and the customizations/overrides can happen on the task run only.

Task registration logic can be up the user via custom code in Python or perhaps Terraform.

### Example

Here is an example of what the usage would look like:

```python
ecs_block = ECSTask(
            name=block_name,
            task_definition_arn=self._handle_task_definition(),
            cluster=f"prefect-v2-agent-{ENVIRONMENT_TYPE}-{DEPLOYMENT_TYPE}",
            launch_type="FARGATE",
            allow_task_definition_registration=False,
        )
```

### Screenshots

New docs:

image

Here is what the agent logs look like:

image

Here is the successful flow run:

image

### Checklist

- [X] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-aws/issues/new/choose) first.
- [X] Includes tests or only affects documentation.
- [X] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [X] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [x] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-aws/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by madkinsz** [comment]
@braunreyes I feel like we want to still read the task definition and raise an exception if the settings you've provided are not compatible. Otherwise people are going to tweak settings that require a change to the task definition and not understand why those settings are not being respected. Thoughts?

**Comment by braunreyes** [comment]
@madkinsz  Do you think moving this out of the else will suffice?

```python
task_definition = self._prepare_task_definition(
                requested_task_definition, region=ecs_client.meta.region_name
            )
```

It will do a bunch of overriding that doesn't get used and produces a task definition that does not exactly match what will be used on the flow.  Also the only exception raised is this:

```python
raise ValueError(
                "An execution role arn must be set on the task definition to use "
                "`configure_cloudwatch_logs` or `stream_logs` but no execution role "
                "was found on the task definition."
            )
```

Seems like they are all basic task registration items that would be found when handling task registration yourself.

The only thing that seems Prefect specific is `PREFECT_ECS_CONTAINER_NAME` so that overrides on the task run work.

I can add an exception for that in my if statement.

```python
# ignore task definition handling if allow_task_definition_registration is False
        if not self.allow_task_definition_registration:
            if not task_definition_arn:
                raise ValueError(
                    "A task_definition_arn value must be provided to "
                    "disable task definition registration"
                )
            container = get_prefect_container(
                requested_task_definition.get("containerDefinitions", [{}])
            )
            if container is None:
                raise ValueError(
                    "'name' in the prefect container definition "
                    "must be equal to PREFECT_ECS_CONTAINER_NAME"
                )

            self.logger.info(
                f"{self._log_prefix}: Task definition registration is disabled..."
            )
            self.logger.info(
                f"{self._log_prefix}: Predefined task definition will be used as is..."
            )
            task_definition = requested_task_definition
```

**Comment by braunreyes** [comment]
My thought process behind the new argument is that you should not expect task registration settings to do anything

**Comment by braunreyes** [comment]
@madkinsz let me know what you think about my latest comments.  Could even add in the docs that fields specific to task registration will not have any effect.

**Comment by braunreyes** [comment]
@madkinsz just a bump on my last comment.  I am using the set of changes in our Pocket fork and it is working as expected.

**Pull request closed without merging**
