### PR TITLE
Add block for ECR

### PR DESCRIPTION
**Pull request by madkinsz**
## Summary

Implementation of an ECR version of https://github.com/PrefectHQ/prefect/pull/6303

Requires https://github.com/PrefectHQ/prefect/pull/6328, and consequently` prefect>=2.1.0.`

## Relevant Issue(s)

Closes https://github.com/PrefectHQ/prefect/issues/6230

### CODE REVIEW

**Comment by madkinsz** [comment]
Can someone explain to me how coverage works? It's telling me that functions aren't covered even though they definitely are.

**Comment by desertaxle** [comment]
> Can someone explain to me how coverage works? It's telling me that functions aren't covered even though they definitely are.

Can you post a coverage report so that we can see what it's claiming isn't covered?

**Comment by madkinsz** [comment]
```
interrogate..............................................................Failed
- hook id: interrogate
- exit code: 1

= Coverage for /Users/mz/dev/prefect-aws/prefect_aws/ =
- Detailed Coverage -
| Name                                                       |  Status |
|------------------------------------------------------------|---------|
| ecr.py (module)                                            |  MISSED |
|   ElasticContainerRegistry (L13)                           | COVERED |
|     ElasticContainerRegistry.login (L28)                   |  MISSED |
|     ElasticContainerRegistry._login_sync (L31)             |  MISSED |
|     ElasticContainerRegistry._parse_token (L37)            | COVERED |
|     ElasticContainerRegistry._get_client (L45)             |  MISSED |
|     ElasticContainerRegistry._get_token_and_endpoint (L48) |  MISSED |
|------------------------------------------------------------|---------|

- Summary -
| Name   | Total | Miss | Cover | Cover% |
|--------|-------|------|-------|--------|
| ecr.py |     7 |    5 |     2 |    29% |
|--------|-------|------|-------|--------|
| TOTAL  |    36 |    5 |    31 |  86.1% |
|-------------------------------------------------|
| (5 of 6 files omitted due to complete coverage) |
- RESULT: FAILED (minimum: 95.0%, actual: 86.1%) -
```

**Comment by madkinsz** [comment]
```
❯ pytest --cov-report term --cov=prefect_aws.ecr tests/test_ecr.py
=========================================================================================================== test session starts ============================================================================================================
platform darwin -- Python 3.8.3, pytest-7.1.2, pluggy-0.13.1
rootdir: /Users/mz/dev/prefect-aws, configfile: setup.cfg
plugins: anyio-3.6.1, xdist-2.5.0, forked-1.4.0, env-0.6.2, flaky-3.7.0, asyncio-0.19.0, timeout-2.1.0, respx-0.19.2, flakefinder-1.0.0, cov-3.0.0
asyncio: mode=auto
collected 4 items                                                                                                                                                                                                                          

tests/test_ecr.py ....                                                                                                                                                                                                               [100%]

---------- coverage: platform darwin, python 3.8.3-final-0 -----------
Name                 Stmts   Miss  Cover   Missing
--------------------------------------------------
prefect_aws/ecr.py      37      0   100%
--------------------------------------------------
TOTAL                   37      0   100%

Required test coverage of 80.0% reached. Total coverage: 100.00%```

**Comment by desertaxle** [comment]
Ah `interrogate` is failing due to lack of docstring coverage. It looks like there are few methods on `ElasticContainerRegistry` that need docstrings. Test coverage looks great!

**Comment by madkinsz** [comment]
Oh that's what it's asking for 🤦 we're enforcing docstrings on private methods?

**Comment by desertaxle** [comment]
Enforcing docstrings on private methods appears to be the default behavior for `interrogate`. You can add `ignore-semiprivate = true` to `setup.cfg` to override that behavior.

**Comment by anna-geller** [comment]
This looks awesome, love this token expiration handling magic, so cool! Currently QAing this, will update soon

**Comment by madkinsz** [comment]
This is blocked pending a proper implementation of https://github.com/PrefectHQ/prefect/pull/6478

**Comment by feliperazeek** [comment]
@zanieb what happened to this code? doesn't seem to be on master, thank you!

**Comment by zanieb** [comment]
@feliperazeek this was not merged due to changes in the upstream design and this branch was deleted so this code is no longer available.

**Pull request closed without merging**
